run_name: "potato_friends_sentiment_dynamic_graph"

paths:
  init_memes: "data/init_memes.txt"

graph_generation:
  type: 'small_worlds'  # 'example' or 'small_worlds'
  initial_meme_assignment: 'random'  # Initial assignment of memes to nodes: 'random' or 'structured'
  params:  # For small_worlds
    g: 1       # Number of groups
    n: 10      # Nodes per group
    k: 4       # 4 Each node is joined with its k nearest neighbors in ring topology
    p: 0.4     # Probability of rewiring each edge
    b: 0.8     # Probability of adding a backward edge
    inter_p: 0.05  # Probability of inter-group connection

dynamic_graph:
  enabled: true
  initial_static_generations: 10
  actions:
    - type: 'death'
      enabled: true
      check_every_n_generations: 1
      params:
        consecutive_generations_threshold: 2
        fitness_percentile_threshold: 0.15 # Bottom 15%
    - type: 'fusion'
      enabled: true
      check_every_n_generations: 1
      params:
        similarity_threshold: 0.97 # Min similarity for fusion
    - type: 'division'
      enabled: true
      check_every_n_generations: 1
      params:
        max_graph_nodes: 300
        # To consider division, a node must have at least this many in/out connections
        min_in_degree: 2
        min_out_degree: 2
        fitness_top_percent: 0.2 # Top 20% fittest nodes are candidates
        connection_subset_ratio: 0.5

simulation:
  generations: 500
  threshold: 0.2  # Score ratio threshold for merge/mutate/keep decision
  selection_strategy: 'fitness_similarity_product' # 'fitness' or 'fitness_similarity_product'
  merge_converge_similarity_threshold: 0.9 # Min similarity for converge merge
  merge_influence_similarity_threshold: 0.5 # Min similarity for influence merge
  initial_score: true  # Whether to score initial memes before first generation
  fitness_model_huggingpath: 'cardiffnlp/twitter-roberta-base-sentiment-latest' # path to a model on huggingface (e.g. 'cardiffnlp/twitter-roberta-base-sentiment-latest'), or empty string ('') -> using LLM with prompt_score below

llm:
  huggingpath: "microsoft/Phi-3-mini-4k-instruct"
  # api_key: "YOUR_API_KEY"  # Optional: Add API key if needed for a certain model/API
  temperature_mutate: 0.7
  temperature_merge: 0.4
  temperature_score: 0.2
  max_new_tokens: 50  # Hardcoded 1 for scoring
  prompt_mutate: |
    Make a very small change to the user's sentence that slightly changes its meaning, style, or tone. Keep the topic and length about the same.
    Output ONLY the changed sentence.
  prompt_merge_converge: |
    Change the user's sentence to be closer in meaning to the example sentence. Keep the user's topic and length about the same.
    Output ONLY the changed sentence.
  prompt_merge_influence: |
    Make a very small change to the user's sentence that slightly changes its meaning, style, or tone. Keep the topic and length about the same.
    Use the example sentence only as inspiration, but do NOT copy or switch to its topic.
    Output ONLY the changed sentence.
  prompt_score: |
    Rigorously evaluate the user's text for virality on a strict 0 to 9 scale based on these criteria:
    - Immediate attention-grabbing appeal
    - Strong emotional response or high relatability
    - Clear and concise messaging, easy to share and understand
    - High potential for discussion, controversy, or widespread interest
    Rating Scale Guidelines:
    9 Exceptional: Highly shareable, evokes strong emotions, and sparks conversation instantly.
    8 Outstanding: Compelling, emotionally engaging, and likely to be widely spread.
    7 Excellent: Strongly resonates with audiences, though slightly less universally viral.
    6 Strong: Attention-grabbing and interesting but not overwhelmingly shareable.
    5 Good: Holds interest and has some viral potential but lacks a strong hook.
    4 Acceptable: Somewhat engaging but unlikely to gain significant traction.
    3 Weak: Passable but lacks the elements needed for virality.
    2 Poor: Struggles to generate interest or lacks clear viral appeal.
    1 Very Poor: Unlikely to be shared due to weak impact or unclear messaging.
    0 Non-viral: Completely fails to capture attention or interest.
    Output only the text rating.

embeddings:
  model_path: "sentence-transformers/all-mpnet-base-v1"  # For text embeddings (used for visualizations and similarity)
  #    "sentence-transformers/all-roberta-large-v1"
  #    "bert-base-uncased"  

visualization:
  # Per-generation plots
  draw_change_per_gen: true
  draw_score_per_gen: true
  plot_score_history_individual: true
  draw_semantic_diff_per_gen: false
  # Final plots
  draw_final_embs: true
  plot_final_score_history_by_group: true
  plot_score_history_by_initial_meme: true
  plot_semantic_drift: false
  plot_semantic_centroid_distance_drift: false
  # Plot settings
  node_min_size: 20
  node_max_size: 400
  edge_base_thickness: 1.0
  edge_base_opacity: 0.5
  label_max_len: 64
  dpi: 150

seed: 1

logging:
  level: "INFO" # Levels: DEBUG, INFO, WARNING, ERROR, CRITICAL